version: '3'
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '3306:3306'
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql-data:/var/lib/mysql
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/my_portfolio
      # https://qiita.com/shotat/items/57d049793605ffc20135
      - bundle:/usr/local/bundle:cached
      - node_modules:/my_portfolio/node_modules
      - /my_portfolio/vendor
      - /my_portfolio/tmp
      - /my_portfolio/log
      - /my_portfolio/.git
    ports:
      - "3000:3000"
    depends_on:
      - db
    stdin_open: true
    tty: true
volumes:
  bundle:
    driver: local
  mysql-data:
    driver: local
  node_modules: