version: "3"

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
    networks:
      - default
    ports:
      - '33306:3306'
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: portfolio_app
    ports:
      - '3000:3000'
    environment:
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: password
      MYSQL_HOST: mysql
    depends_on:
      - db
    networks:
      - default
    command: bundle exec rails server -b 0.0.0.0