:pidfile: ./tmp/pids/sidekiq.pid
:logfile: ./log/sidekiq.log
:queues:
  - task
  - default
  - slow


:schedule:
  UpdatePerformanceJob:
    every: 6h
    class: UpdatePerformanceJob

  SendDayBeforeMailJob:
    cron: "0 0 17 * * *"
    class: SendDayBeforeMailJob
